[2023-02-03T06:57:48.285+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [queued]>
[2023-02-03T06:57:48.303+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [queued]>
[2023-02-03T06:57:48.304+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T06:57:48.304+0200] {taskinstance.py:1280} INFO - Starting attempt 6 of 8
[2023-02-03T06:57:48.304+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T06:57:48.357+0200] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-15 10:29:20.696392+00:00
[2023-02-03T06:57:48.369+0200] {standard_task_runner.py:55} INFO - Started process 51287 to run task
[2023-02-03T06:57:48.381+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'manual__2023-01-15T10:29:20.696392+00:00', '--job-id', '589', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmpbn99l8od']
[2023-02-03T06:57:48.387+0200] {standard_task_runner.py:83} INFO - Job 589: Subtask etl_pipeline
[2023-02-03T06:57:48.606+0200] {task_command.py:388} INFO - Running <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-02-03T06:57:48.891+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-15T10:29:20.696392+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-15T10:29:20.696392+00:00
[2023-02-03T06:58:12.021+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 107, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-02-03T06:58:12.031+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230115T102920, start_date=20230203T045748, end_date=20230203T045812
[2023-02-03T06:58:12.042+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 589 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 51287)
[2023-02-03T06:58:12.049+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-03T06:58:12.065+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
