[2023-01-15T12:34:14.922+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [queued]>
[2023-01-15T12:34:14.975+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [queued]>
[2023-01-15T12:34:14.977+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:34:14.979+0200] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-15T12:34:14.980+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:34:15.016+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-15 10:29:20.696392+00:00
[2023-01-15T12:34:15.033+0200] {standard_task_runner.py:55} INFO - Started process 49225 to run task
[2023-01-15T12:34:15.042+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'manual__2023-01-15T10:29:20.696392+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmp0vo4jke4']
[2023-01-15T12:34:15.048+0200] {standard_task_runner.py:83} INFO - Job 532: Subtask etl_pipeline
[2023-01-15T12:34:15.818+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T12:34:15.965+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-15T10:29:20.696392+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-15T10:29:20.696392+00:00
[2023-01-15T12:35:23.137+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 113, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-01-15T12:35:23.269+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230115T102920, start_date=20230115T103414, end_date=20230115T103523
[2023-01-15T12:35:23.346+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 532 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 49225)
[2023-01-15T12:35:23.394+0200] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-15T12:35:23.567+0200] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
