[2023-01-15T12:22:12.227+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.visualize_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-15T12:22:12.281+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.visualize_data scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-15T12:22:12.288+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:22:12.290+0200] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2023-01-15T12:22:12.291+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:22:12.411+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): visualize_data> on 2023-01-01 00:00:00+00:00
[2023-01-15T12:22:12.448+0200] {standard_task_runner.py:55} INFO - Started process 41878 to run task
[2023-01-15T12:22:12.507+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'visualize_data', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '496', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmp5papwaz9']
[2023-01-15T12:22:12.543+0200] {standard_task_runner.py:83} INFO - Job 496: Subtask visualize_data
[2023-01-15T12:22:13.845+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.visualize_data scheduled__2023-01-01T00:00:00+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T12:22:14.468+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=visualize_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:00:00+00:00
[2023-01-15T12:22:14.917+0200] {logging_mixin.py:137} INFO -   traincategory_name  number
0         Test drive       1
1           Commuter       3
2  On-track machines       1
3           Shunting       7
4              Cargo       2
5      Long-distance      14
6         Locomotive       1
[2023-01-15T12:22:14.920+0200] {python.py:177} INFO - Done. Returned value was:   traincategory_name  number
0         Test drive       1
1           Commuter       3
2  On-track machines       1
3           Shunting       7
4              Cargo       2
5      Long-distance      14
6         Locomotive       1
[2023-01-15T12:22:15.034+0200] {xcom.py:629} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2023-01-15T12:22:15.042+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2294, in xcom_push
    XCom.set(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/xcom.py", line 234, in set
    value = cls.serialize_value(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-01-15T12:22:15.173+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=visualize_data, execution_date=20230101T000000, start_date=20230115T102212, end_date=20230115T102215
[2023-01-15T12:22:15.360+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 496 for task visualize_data (Object of type DataFrame is not JSON serializable; 41878)
[2023-01-15T12:22:15.396+0200] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-15T12:22:15.704+0200] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
