[2023-02-03T06:44:32.387+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T09:05:54.099227+00:00 [queued]>
[2023-02-03T06:44:32.419+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T09:05:54.099227+00:00 [queued]>
[2023-02-03T06:44:32.420+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T06:44:32.421+0200] {taskinstance.py:1280} INFO - Starting attempt 7 of 8
[2023-02-03T06:44:32.421+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T06:44:32.443+0200] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-15 09:05:54.099227+00:00
[2023-02-03T06:44:32.454+0200] {standard_task_runner.py:55} INFO - Started process 47893 to run task
[2023-02-03T06:44:32.468+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'manual__2023-01-15T09:05:54.099227+00:00', '--job-id', '562', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmp378ujual']
[2023-02-03T06:44:32.471+0200] {standard_task_runner.py:83} INFO - Job 562: Subtask etl_pipeline
[2023-02-03T06:44:32.618+0200] {task_command.py:388} INFO - Running <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T09:05:54.099227+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-02-03T06:44:32.772+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-15T09:05:54.099227+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-15T09:05:54.099227+00:00
[2023-02-03T06:45:36.530+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 107, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-02-03T06:45:36.595+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230115T090554, start_date=20230203T044432, end_date=20230203T044536
[2023-02-03T06:45:36.628+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 562 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 47893)
[2023-02-03T06:45:36.649+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-03T06:45:36.718+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
