[2023-01-15T02:10:31.996+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v01.train_res_df manual__2023-01-14T23:23:00.798667+00:00 [queued]>
[2023-01-15T02:10:32.083+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v01.train_res_df manual__2023-01-14T23:23:00.798667+00:00 [queued]>
[2023-01-15T02:10:32.085+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T02:10:32.086+0200] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2023-01-15T02:10:32.088+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T02:10:32.138+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): train_res_df> on 2023-01-14 23:23:00.798667+00:00
[2023-01-15T02:10:32.180+0200] {standard_task_runner.py:55} INFO - Started process 37251 to run task
[2023-01-15T02:10:32.256+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v01', 'train_res_df', 'manual__2023-01-14T23:23:00.798667+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmpvcdajnqr']
[2023-01-15T02:10:32.265+0200] {standard_task_runner.py:83} INFO - Job 97: Subtask train_res_df
[2023-01-15T02:10:33.036+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v01.train_res_df manual__2023-01-14T23:23:00.798667+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T02:10:33.903+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v01
AIRFLOW_CTX_TASK_ID=train_res_df
AIRFLOW_CTX_EXECUTION_DATE=2023-01-14T23:23:00.798667+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-14T23:23:00.798667+00:00
[2023-01-15T02:14:37.593+0200] {python.py:177} INFO - Done. Returned value was: DataFrame[name: string, trainCategory_name: string]
[2023-01-15T02:14:38.157+0200] {xcom.py:629} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2023-01-15T02:14:38.193+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2294, in xcom_push
    XCom.set(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/xcom.py", line 234, in set
    value = cls.serialize_value(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-01-15T02:14:38.311+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v01, task_id=train_res_df, execution_date=20230114T232300, start_date=20230115T001032, end_date=20230115T001438
[2023-01-15T02:14:38.514+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 97 for task train_res_df (Object of type DataFrame is not JSON serializable; 37251)
